#!/bin/bash

server=${VIVO_SERVER:-http://localhost:8080}
endpoint="$server/vivo/api/sparqlQuery"
email=${VIVO_EMAIL:-vivo_root@umd.edu}
password=$VIVO_PASSWORD

query=${1:-"SELECT ?s ?p ?o WHERE { ?s ?p ?o } LIMIT 10"}
shift

curl -X POST "$endpoint" \
    -d query="$query" -d email="$email" -d password="$password" "$@"
